### ISSUE TITLE
filter or exclude ns

### ISSUE THREAD

**Issue by JuanSeBestia** [storax/kubedoom#11]
I have some ns that I do not want to be touched, because the pods take a long time to upload, so I want to filter them or exclude them

**Comment by cpressland** [comment]
@JuanSeBestia - I've opened a PR which covers _half_ of this, it doesn't allow excluding as `kubectl` doesn't have a mechanism for saying "Give me everything except this thing", but I can limit namespace scope easy enough. 

In a perfect world I'd actually replace the entire kubectl interface with a kube library, that'd be faster and allow us to make better decisions such as excluding specific things, but, thats a lot of work for very little gain.

Fingers crossed @storax merges and releases this, but failing that my build of this is available here [cpressland/kubedoom](https://hub.docker.com/r/cpressland/kubedoom)
