### ISSUE TITLE
GitHub Actions and native ARM64 Support

### ISSUE THREAD

**Issue by cpressland** [storax/kubedoom#15]
@storax would a pull request be welcome to add arm64 and GitHub Actions + GitHub Packages support?

I'll be doing a Chaos Engineering demo soon, the plan is to use Kube, Kubedoom, Buoyant Cloud, Linkerd, etc to show service resilience during turbulent operation. arm64 support is pretty critical for this as I use an arm MacBook as my primary workstation.

I have modified the Dockerfile locally to enable this to mostly work alongside a few quality of life improvements, adding GitHub Actions just makes this easier and quicker to build.

**Comment by storax** [comment]
That sounds great! It will make it easily accessible to more people. A contribution would be more than welcome.

**Comment by cpressland** [comment]
@storax - opened #16, if you're happy with it all you'll need to do once merged is make a git tag thats semver compliant and it'll automatically run a build.

**Comment by storax** [comment]
@cpressland, thank you very much for your contribution! I've updated the readme and released 0.6.0.
See https://github.com/storax/kubedoom/pkgs/container/kubedoom for the newly built images.
