### ISSUE TITLE
Kube Doom in own Kube cluster

### ISSUE THREAD

**Issue by Totor78** [storax/kubedoom#2]
Hi, 
I would use your repo in my own kube cluster. So I just use files in manifest directory and create service file and ingress. It does'nt work, should I add in my kube config :
extraPortMappings:
  - containerPort: 5900
    hostPort: 5900
    listenAddress: "127.0.0.1"

Best regards,
Rémi

**Comment by storax** [comment]
Please provide more details about what exactly doesn't work.

**Comment by Totor78** [comment]
Im sorry I was using K3s 1.16.X, that was the problem
