### ISSUE TITLE
Delete namespace instead of pods

### ISSUE THREAD

**Issue by siorellana** [storax/kubedoom#5]
Hi.
We have a DEV cluster with more of 2500 namespace, we want use this tool to delete them with the Thanos philosophy.
How can we set this option?
Thanks and regards.

**Comment by storax** [comment]
Nice DEV cluster. Give me a minute, I'll release a new version where you can change the mode to kill namespaces. It's all handled within kubedoom.go.

**Comment by storax** [comment]
I've released storaxdev/kubedoom:0.4.0. You can switch to killing namespaces by supplying the `-mode namespaces` flag. If you are using the manifest from the repository, you'd have to add the flag in the deployment.
The Readme has been updated as well with instructions. Let me know how it goes.
I have absolutely no idea how this would handle 2500 namespaces :smiley:.

**Comment by siorellana** [comment]
Thank you very much for your help.
We are now trying to run this in the DEV cluster, this will help us to make a fun clean up of the namespaces.

Best regards.
