### ISSUE TITLE
Kubedoom kills itself

### ISSUE THREAD

**Issue by torblerone** [storax/kubedoom#7]
Hello, I've run your Tool inside a *Minikube* Cluster and I'm quite happy with it, it's a very fun way to show people Chaos Engineering on a lower, funnier level than just simple code.

It just appears to me that sometimes, I kill the `kubedoom` Pod itself. Is it possible to prevent spawning a Demon in Doom that stands for the Kubedoom-Pod? 

Or is it even possible to exclude more Pods (like from `kubesystem` namespace) from being spawned in kubedoom?

Anyway, thank you for keeping the project up and running!

**Comment by storax** [comment]
The easiest solution is to not use Kubedoom within a Pod but to run it outside your cluster as a docker container as described in the Readme. Potentially, it could also be solved by excluding the kubedoom pod but it's up to you how you name that pod if you are not using the example manifest, so probably would require adding an exclude arg so it can be configurable.

You could also try restricting access to the kubedoom service account with RBAC and only allow it to kill certain pods in certain namespaces. I haven't tested it but it could make the kubesystem demons immortal ;) Also haven't tested the idea of restricting the list pods permissions to certain namespaces. Kubedoom essentially runs "kubectl list pods --all-namespaces". I'm not sure how that behaves when some namespaces are restricted but could be worth a shot to hide those pods.

**Comment by torblerone** [comment]
Thank you for your input. Running kubedoom outside of the cluster solved the problem of killing itself.
Just as you predicted, restricting kubedoom with RBAC makes certain demons immortal and makes it not funny.
